In [21]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [27]:
data = pd.read_csv("final_data.csv")

In [28]:
data.head()

Unnamed: 0.1  Unnamed: 0  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
0             0           0   0            5.1           3.5            1.4   
1             1           1   1            4.7           3.2            1.6   
2             2           2   2            4.9           3.1            1.5   
3             3           3   3            4.4           2.9            1.4   
4             4           4   4            5.0           3.4            1.5   

   PetalWidthCm      Species  
0           0.2  Iris-setosa  
1           0.2  Iris-setosa  
2           0.1  Iris-setosa  
3           0.2  Iris-setosa  
4           0.2  Iris-setosa

In [29]:
data.drop(["Unnamed: 0.1","Unnamed: 0","Id"], axis = 1, inplace = True)
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.7           3.2            1.6           0.2  Iris-setosa
2            4.9           3.1            1.5           0.1  Iris-setosa
3            4.4           2.9            1.4           0.2  Iris-setosa
4            5.0           3.4            1.5           0.2  Iris-setosa

Label Encoding

In [30]:
le = LabelEncoder()

In [33]:
data["Species"] = le.fit_transform(data["Species"])

In [34]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

In [35]:
data.to_csv("modelv2.csv")

##Veri Kontrolleri

In [46]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [48]:
data.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int64
dtype: object

In [49]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

## Train Test Split

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train, x_test, y_train, y_test = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size=0.2)

In [54]:
x_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
127            7.4           2.8       6.100000           1.9
130            6.1           3.0       4.900000           1.8
101            6.1           3.0       4.600000           1.4
3              4.4           2.9       1.400000           0.2
106            5.5           2.4       3.700000           1.0
131            6.5           3.0       5.500000           1.8
88             5.9           3.0       4.200000           1.5
152            6.7           3.3       5.700000           2.5
9              4.7           3.2       1.300000           0.2
123            7.7           3.8       6.700000           2.2
58             5.3           3.7       1.500000           0.2
28             5.2           3.4       1.400000           0.2
161            6.7           3.0       5.200000           2.3
97             5.0           2.3       3.300000           1.0
24             5.7           3.8       1.700000           0.3
82             5.9           3.2       4.800000           1.8
92             6.7           3.1       4.700000           1.5
169            6.3           3.3       6.000000           2.5
98             6.3           3.3       3.707229           1.6
154            6.3           2.7       4.900000           1.8
1              4.7           3.2       1.600000           0.2
91             6.3           2.3       4.400000           1.3
20             5.8           4.0       1.200000           0.2
112            5.7           2.8       4.100000           1.3
77             6.4           2.9       4.300000           1.3
80             6.3           2.5       4.900000           1.5
34             4.8           3.1       1.600000           0.2
99             5.7           3.0       4.200000           1.2
113            6.1           2.9       3.707229           1.4
49             5.1           3.8       1.600000           0.2
100            5.7           2.9       4.200000           1.3
50             5.1           3.8       3.707229           0.2
41             4.5           2.3       1.300000           0.3
30             4.8           3.0       1.400000           0.1

In [55]:
y_train.value_counts()

Species
2    48
0    48
1    40
Name: count, dtype: int64

In [56]:
y_test.value_counts()

Species
1    14
0    12
2     8
Name: count, dtype: int64

## Modelin Oluşturulması

In [57]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/150.0 MB ? eta -:--:--
   ---------------------------------------- 0.8/150.0 MB 1.5 MB/s eta 0:01:38
   ---------------------------------------- 0.8/150.0 MB 1.5 MB/s eta 0:01:38
   ---------------------------------------- 1.3/150.0 MB 1.6 MB/s eta 0:01:32
   ---------------------------------------- 1.8/150.0 MB 1.6 MB/s eta 0:01:32
    --------------------------------------- 2.1/150.0 MB 1.6 MB/s eta 0:01:35
    --------------------------------------- 2.4/150.0 MB 1.6 MB/s eta 0:01:33
    --------------------------------------- 2.6/150.0 MB 1.6 MB/s eta 0:01:32
    --------------------------------------- 3.1/150.0 MB 1.6 MB/s eta 0:01:31
    --------------------------------------- 3.4/150.0 MB 1.6 MB/s eta 0:01:30
    ---


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [58]:
import xgboost as xgb

In [59]:
xgb_cls = xgb.XGBClassifier(objective="multiclass:softmax", num_class=3, use_label_encoder=False)

In [60]:
xgb_cls.fit(x_train, y_train, use_label_encoder=False)

C:\Users\Hasan\AppData\Roaming\Python\Python313\site-packages\xgboost\training.py:183: UserWarning: [14:57:29] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_class=3, ...)

In [61]:
preds = xgb_cls.predict(x_test)

In [62]:
preds

array([2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 1, 2, 1, 2, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0])

In [63]:
import numpy as np

In [64]:
np.array(y_test)

array([2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 0, 0, 2, 1, 0, 1, 1, 2, 1, 2, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0])

In [65]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [66]:
accuracy_score(y_test, preds)

0.9705882352941176

In [67]:
confusion_matrix(y_test, preds)

array([[12,  0,  0],
       [ 0, 13,  1],
       [ 0,  0,  8]])